#!/usr/bin/bash
#
# Run the scanner with two test programs and examine the results
#
count=$(wc -l $1-1.txt | awk '{print $1}')
echo $count should be 236
rm -f $1-out1.txt
awk 'NR > 3 {print $1, $2}' $1-1.txt > $1-out1.txt
diff $1-out1.txt sample.output
count=$(wc -l $1-2.txt | awk '{print $1}')
echo $count should be 18
rm -f $1-out2.txt
awk 'NR > 3 {print $1, $2}' $1-2.txt > $1-out2.txt
diff $1-out2.txt t1.output
echo '***'
cat $1-2.txt
rm -f output.txt
